[package]
name = "crossbash"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
termion = "1.5.6"
signal-hook = "0.3"
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
dotenv = "0.15"
diesel = { version = "1.4.8", features = ["postgres", "chrono", "uuid", "serde_json"] }
async-std = "1.10.0"
uuid = { version = "0.6.5", features = ["serde", "v4"] }
prometheus = "0.12"
actix-web-prom = "0.5.0-beta.5"
fern = "0.6"
log = "0.4"
once_cell = "1.8.0"
strum = { version = "0.21", features = ["derive"] }
strum_macros = "0.21"
geo = "0.17"  # Check for the latest version that suits your needs
geo-types = "0.7"  # For geospatial primitives
simplelog = "0.11"
lazy_static = "1.4"
tempfile = "3.2"
crossterm = "0.22"
env_logger = "0.10"
petgraph = "0.5"
clap = "3.2.0"

[dependencies.reqwest]
version = "0.11"
features = ["rustls-tls"]

[[bin]]
name = "crossbash"
path = "src/main.rs"
