# BoxMux Site Configuration

title: BoxMux
description: A YAML-driven terminal UI framework for creating rich, interactive CLI applications and dashboards.
url: https://boxmux.com
baseurl: /

# GitHub Pages settings
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
navigation:
  - title: Getting Started
    url: /getting-started
  - title: Configuration
    url: /configuration
  - title: Examples
    url: /examples
  - title: API Reference
    url: /api
  - title: Contributing
    url: /CONTRIBUTING
  - title: Roadmap
    url: /roadmap

# Site settings
author:
  name: Bahram Joharshamshiri
  email: bahram@example.com
  github: jowharshamshiri

# SEO settings
logo: /assets/images/boxmux-logo.png
social:
  name: BoxMux
  links:
    - https://github.com/jowharshamshiri/boxmux
    - https://twitter.com/boxmux

# Build settings
markdown: kramdown
highlighter: rouge
source: .
destination: _site
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# GitHub repository
github:
  repository_url: https://github.com/jowharshamshiri/boxmux
  repository_name: boxmux
  owner_name: jowharshamshiri
  
# Features
features:
  - title: "YAML-Driven"
    description: "Define your entire interface using simple, readable YAML configuration"
    icon: "📝"
  - title: "Real-time Updates"
    description: "Built-in refresh intervals and live data streaming"
    icon: "⚡"
  - title: "Interactive"
    description: "Keyboard navigation, menu selection, and custom keybindings"
    icon: "🎛️"
  - title: "Cross-platform"
    description: "Works on macOS, Linux, and other Unix-like systems"
    icon: "📱"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - target/
  - .gitignore
  - .git/
  - serve.sh
  - _config_dev.yml

# Include files that start with underscore
include:
  - _layouts
  - _includes